### PR TITLE
Adding PickUpAndHold script and adding gender neutral language to the Editor scripts

### PR DESCRIPTION
**Pull request by sophiaaar**
Also adding a RemoveOnePoint method to UIScript

### CODE REVIEW

**Comment by ciro-unity** [comment]
That's a great addition! I gave a quick review to the code, seems fine.
I just want to change a couple of things (for instance, right now the Inspector shows the warning in any case). Will pull it in when I have time to review the code more in depth.

**Comment by sophiaaar** [comment]
Oh I didn't realise all of my commits had gone into this PR 😓 I thought I was just adding 
115c88b!

**Comment by sophiaaar** [comment]
*nudge* @ciro-unity

**Comment by sophiaaar** [comment]
Added the ability to change (in the inspector) which key is used for picking up and dropping

**Pull request merged**
